### ISSUE TITLE
Keyboard layout has changes. I cannot type double quotes.

### ISSUE THREAD

**Issue by n0yal** [gabrielzschmitz/dotfiles#3]
After installing your setup keyboard layout has changes . When i type double quotes iam getting other symbol . Where is the file for fixing this ?

**Comment by gabrielzschmitz** [comment]
That happens because I'm from Brazil, and we need this type of accents. So I've wrote a script to make the system follow the right keyboard layout for us.
If you don't need that, as you've said, you can just remove that line from i3 config (localized in ~/.config/i3/config):
`exec_always --no-startup-id sh ~/.scripts/kblayout.sh`
and remove the script from your computer:
`rm ~/.scripts/kblayout.sh`
